.gitignore, spec/inputs/jdbc_spec.rb
This PR make all specs to pass in a more consistent way as it was before, now all are green also in linux environments as our beloved jenkins.
The main problem was the time needed to kill the thread used to run the plugin within the test example, in our test environment it got kill slightly after 3 seconds passed (the desired time frame), so at the end this end up on not having the desired number of events.
To "workaround" this situation for now I propose to call the teardown method just after the sleep call, so the scheduler is off, and not rely on  thread.kill to stop the pipeline properly and on time.
I also added the generated logs to the gitignore file.
So what do you think @talevy ?
=> Fixes failing specs

lib/logstash/inputs/jdbc.rb
Logstash documentation is generated using asciidoc, not markdown. This change attempts to fix the syntax towards asciidoc
=> fix asciidoc header syntax

lib/logstash/inputs/jdbc.rb, lib/logstash/plugin_mixins/jdbc.rb, spec/inputs/jdbc_spec.rb
This means slightly different things depending on the vendor and its JDBC driver implementation. Still collecting proven updated information about each vendor's implementation so this can be documented further
=> add jdbc fetch size param to queries

lib/logstash/inputs/jdbc.rb
Currently, if a query is still running while the scheduler
triggers a new query to be executed, the new query will be launched.
This means that two queries will be running at the same time, this can
cause consistency issues. By setting the max_work_threads to `1`, all
newly triggered queries will be added to a work queue within Rufus and
launched immedietly proceeding the completion of the existing pending
job.
=> prevents multiple queries from being run at the same time.

lib/logstash/plugin_mixins/jdbc.rb, spec/inputs/jdbc_spec.rb
this issue was found with using Logstash's Password class to wrap the password string.
ref: https://github.com/logstash-plugins/logstash-input-jdbc/issues/62#issuecomment-150103578
this commit extracts the string value of the password and passes that to Sequel.
=> pass password as string to Sequel

lib/logstash/plugin_mixins/jdbc.rb, spec/inputs/jdbc_spec.rb
As requested in #61 this PR add more information to the debug log statements and also expose the sql_log_level variable from sequel.
Fixes #61
=> Increase log verbosity and levels of information

README.md, lib/logstash/inputs/jdbc.rb, lib/logstash/plugin_mixins/jdbc.rb, spec/inputs/jdbc_spec.rb
add `jdbc_password_filepath` parameter for reading password from an external file.
Must not be used when `jdbc_password` is set.
=> add jdbc_password_filepath parameter, with tests and docs

lib/logstash/inputs/jdbc.rb, lib/logstash/plugin_mixins/jdbc.rb, spec/inputs/jdbc_spec.rb
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
This allows plugin users to set `use_column_value` on tracking columns
where the column type is a timestamp. Currently, this is only possible
using a numeric column, but there are use cases where the user wants to
select rows from a table where the column value is greater than the last
seen timestamp value of that column.
It turns out that this behaviour works fine with simply setting
`use_column_value` to true on the required column. The only change
needed is to add a flag indicating that on a clean run, the default min
value should be set to `Time.at(0).utc` rather than `0`.
This should close logstash-plugins/logstash-input-jdbc#125
=> Add bool config for tracking column as timestamp

lib/logstash/inputs/jdbc.rb, lib/logstash/plugin_mixins/jdbc.rb, spec/inputs/jdbc_spec.rb
LS 5.0 introduces log4j2 logging, so this PR updates the plugin to support that.
=> fix to be compatible with LS 5.0 core

lib/logstash/inputs/jdbc.rb
As discussed in https://discuss.elastic.co/t/sql-last-value-doesnt-reiterate-with-multiple-jdbc-inputs/63523, this PR represents a doc update to include some guidance on using multiple SQL statements and the importance of last_run_metadata_path parameter when multiple statements also use the sql_last_value parameter for storing state.
=> Added section about using multiple SQL statements

lib/logstash/inputs/jdbc.rb
tracking_colum parameter uses a string
=> tracking_colum parameter uses a string

lib/logstash/inputs/jdbc.rb
According to my understanding what the logstash-input-jdbc plugin do is, get the data from the relational database into the logsash, hence the change.
=> Corrected the meaning of the statement.

CHANGELOG.md, lib/logstash/plugin_mixins/jdbc.rb, logstash-input-jdbc.gemspec
The jdbc input pluging recently got support for automatically reconnecting when a database connection is lost. In this case it tries to cleanly close the old connection by calling disconnect, then setting its @database reference to nil.
@database being nil is then used as an indication that a new connection needs to be opened.
Calling disconnect leads to a call to java.sql.Connection.close() which may throw an SQLException.
In that case @database remains a reference to the broken connection and we try to reuse that.
This PR adds an exception handler to ensure that the database connection is marked dead even when disconnect throws an exception.
=> Mark database connection as dead even when disconnecting fails

lib/logstash/plugin_mixins/jdbc.rb
- DRY up the code that is tracking `sql_last_value`
- when coercing a `sql_last_value` that is a `DateTime`, use `DateTime#to_time` to avoid losing precision
=> Fix issue where `sql_last_value` could lose precision

CHANGELOG.md, lib/logstash/inputs/jdbc.rb, lib/logstash/plugin_mixins/jdbc.rb, lib/logstash/plugin_mixins/value_tracking.rb, logstash-input-jdbc.gemspec, spec/inputs/jdbc_spec.rb
Added three more tests to verify the jdbc_default_timezone behaviour
when no tracking column is specified
when a numeric column is specified
when a timestamp column is specified
Fixes #140
=> Force all usage of sql_last_value to be typed according to the settings

CHANGELOG.md, logstash-input-jdbc.gemspec
d'oh. I should have bumped for release in #291.
=> bump version for release of #291

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/jdbc.rb, lib/logstash/plugin_mixins/jdbc/checked_count_logger.rb, lib/logstash/plugin_mixins/jdbc/jdbc.rb, lib/logstash/plugin_mixins/jdbc/statement_handler.rb, lib/logstash/plugin_mixins/jdbc/value_tracking.rb, logstash-input-jdbc.gemspec, spec/inputs/jdbc_spec.rb
Code, tests, docs and version bump.
=> Add Prepared Statement support

CHANGELOG.md, ci/unit/Dockerfile, ci/unit/docker-compose.yml, ci/unit/run.sh, ci/unit/setup.sql, lib/logstash/plugin_mixins/jdbc/jdbc.rb, logstash-input-jdbc.gemspec, spec/inputs/integ_spec.rb, spec/inputs/jdbc_spec.rb
The changes to class loading intended to fix usage of :jdbc_driver_library with
Java 11, introduced in `v4.3.14`, appear to have some issues
(https://github.com/elastic/logstash/issues/11268, #355). This commit attempts
to resolve those issues, and reworks the integration tests to work with
docker and ensure that the :jdbc_driver_library configuration option works.
This has been tested with postgresql using Java 8 and Java 11.
=> Fix driver class loading

lib/logstash/plugin_mixins/jdbc/jdbc.rb, lib/logstash/plugin_mixins/jdbc/statement_handler.rb
fixes https://github.com/logstash-plugins/logstash-input-jdbc/issues/360
Not a ruby developer by trade so having trouble making the test better.
First PR. I signed CLA after I made this. 
cc @guyboertje
=> Fix jdbc_paging_enabled config flag not being passed through

ci/unit/docker-compose.yml, spec/inputs/integ_spec.rb
Tests were failing due to a change in the latest Postgres docker image
requiring a password to be set by default.
This commit also includes necessary changes to support devutils 2.0
=> Fixed Test Failures
